services:
  - type: web
    name: autonomous-med-assistant-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: autonomous-med-assistant-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui/app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
